version: '3.8'

services:
  web:
    build: ../web
    container_name: vio_web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - relay

  relay:
    build: ../server
    container_name: vio_relay
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=no-reply@vio.test
    depends_on:
      - db
      - redis
      - minio
      - mailhog

  db:
    image: postgres:14
    container_name: vio_db
    environment:
      POSTGRES_USER: vio
      POSTGRES_PASSWORD: vio_pass
      POSTGRES_DB: vio_test
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: vio_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: vio_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"

  mailhog:
    image: mailhog/mailhog
    container_name: vio_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  db_data:
